micronaut:
  application:
    name: mktdata
  server:
    port: 9080

  netty:
    event-loops:
      custom-event-loop:
        num-threads: 20
  http:
    client:
      event-loop-group: custom-event-loop
      read-timeout: 30s

mktdata:
  enable-kafka: false
  watch-list:
    - AAPL
    - AMZN
    - GOOGL
    - META
    - MSFT
    - NVDA
    - TSLA

datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${JDBC_USER:sa}
    password: ${JDBC_PASSWORD:""}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

kafka:
  bootstrap:
    servers: localhost:9092

